### ISSUE TITLE
Create new image

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#14]
For _docker file_ or _docker configuration_, options are:
- [ ] upload button (nuvla/ui#18)
- [ ] link to say GitHub, with ref to GitHub credentials, and _test connection button_ (nuvla/ui#19)
- [ ] edit directly (nuvla/ui#20)

We need to resolve the issue of image build and its life-cycle.

**Comment by mebster** [comment]
Superseded by other issues.
