### ISSUE TITLE
Nuvla v2.0 ui critical requirements

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#41]
In order for Nuvla v2 to support the GNSS CCN Use-Case, we need the following features available from the UI.  This implies corresponding backend features are also available.

## Shared features

These features apply to all personae.

### Registration workflow

Complete the registration workflow.  A few options are possible:

- [x] Port password reset to Nuvla (https://github.com/nuvla/server/issues/27 and https://github.com/nuvla/ui/issues/5)
- [x] Add password change for the _internal method_ (https://github.com/nuvla/ui/issues/1)

### Complete the profile page

- [ ] CRUD for properties (https://github.com/nuvla/ui/issues/2)

Provide CRUD for the following resources:
- [ ] Credentials (cloud/swarm, ssh keys, ...) (https://github.com/nuvla/ui/issues/3 and (https://github.com/nuvla/ui/issues/4)
- [ ] Connectors (read only) (https://github.com/nuvla/ui/issues/4)
- [ ] Email (https://github.com/nuvla/ui/issues/7)
- [ ] ...

## Alice features

This is feature complete, with perhaps the exception of:

- [x] Move the _process_ action button below the cards. (nuvla/ui#8)

## Clara features

These features apply to Clara.

### Module CRUD

(is _module_ the right term?)

- [ ] Enable guided creation of: _project_ and _docker image_ (nuvla/ui#10)

- [ ] _project_ (nuvla/ui#12 and nuvla/ui#13)

- [ ] _docker image_ should expose: (nuvla/ui#14 and nuvla/ui#15)
    1. link to docker hub image, with ref to credentials for docker to download image, and _test connection button_

Issues:
1. How do we recover/populate the service URL?

### Module / data association

- [x] Allow module to _declare_ data it can process (nuvla/ui#21)

### View versions

- [x] Access history (older versions) (nuvla/ui#22)

### App Store population

Sections:
- [x] View all modules via paged cards, with search (nuvla/ui#23)
- [x] View all modules in a hierarchy (aka current application page) (nuvla/ui#24)

### Dataset CRUD

- [ ] Datasets are created by associating a filter with a new _service offer_ (nuvla/ui#25 and nuvla/ui#26)
- [ ] Datasets can be deleted (nuvla/ui#27)

### ACLs

- [x] edit for ACLs, needed for modules (such that Clara can share with Alice) (nuvla/ui#28)
